// App.xaml.cs – WPF application entry point
// This file is auto-generated by Visual Studio and wires up App.xaml.
using System.Configuration;
using System.Data;
using System.Windows;

namespace CyberAwarenessBot
{
    /// <summary>
    /// Interaction logic for App.xaml
    /// This is the application bootstrap – it loads MainWindow on startup.
    /// </summary>
    public partial class App : Application
    {
        // Visual Studio generates this class automatically.
        // No custom logic needed here for Part 3.
    }
}
